### PR TITLE
Add plyvel dependency

### PR DESCRIPTION
**Pull request by manjeetbhatia**
there's a dependency on python module plyvel 1.2.0 which
is not listed in requirements.

### CODE REVIEW

**Comment by anuveyatsu** [comment]
@manjeetbhatia which python version are you using? Please, see github actions here and it works ok with the current requirements.txt - https://github.com/datasets/covid-19/blob/master/.github/workflows/actions.yml#L6-L17

**Comment by manjeetbhatia** [comment]
@anuveyatsu I used 3.6.3 and had issues. documents says 3.6 not the minor so I suppose it should work for all 3.6..* ? https://github.com/datasets/covid-19#preparation .

**Comment by anuveyatsu** [comment]
@manjeetbhatia I'm running v3.6.2 in the virtual env and there is no problem with the dependencies.

**Comment by manjeetbhatia** [comment]
@anuveyatsu here's the trace
 python3 process.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kvfile/kvfile.py", line 5, in <module>
    import plyvel as DB_ENGINE
ModuleNotFoundError: No module named 'plyvel'

here's python version
~/covid/covid-19$ python3
Python 3.6.3 (default, Mar 24 2020, 17:09:42)

**Comment by anuveyatsu** [comment]
Hi @manjeetbhatia I totally understand it, however, we can't merge this PR since it isn't reproducible on other machines. I believe this issue is your environment (python distribution etc.) specific.

**Pull request closed without merging**
