### PR TITLE
Update from 09-05-20

### PR DESCRIPTION
**Pull request by Morisset**

### CODE REVIEW

**Comment by sglavoie** [comment]
Thank you @Morisset. I suspect this was an automatic PR, right? We're all set with the new set up if you want to pull the new script and try it out! It just ran successfully a few hours ago and the processing part took only 2.5 minutes! :tada:.

Again, I thank you very much for the previous PRs you have sent, that was really helpful! However, as you can guess, merging the data now is going to be a mess if we keep the same old script :smile:. In fact, we're confident the new script will work as intended so there is currently no need for you to bother with this automation (not that I would mind receiving them but we'll be forced to close all of them since it won't be mergeable).

Have a good weekend! :wink:

**Comment by Morisset** [comment]
Yep, I'm sorry I did not check this yesterday. I now merged your master to my fork, update my script so it runs the 2 new process files. It should by ok tonight with a pull request of only data files ;-)

**Comment by sglavoie** [comment]
No worries, thank you! In fact, there won't be any need to send pull requests at all since GitHub Actions can now process everything without any issue. You can see [the latest commits](https://github.com/datasets/covid-19/commits/master) were two successful updates from the automated workflow at the time of this writing, so it should be under control now :slightly_smiling_face:.

**Comment by sglavoie** [comment]
Hi @Morisset! I am no longer part of Datopian, who is the maintainer of this repository. The files are getting too large to be uploaded to GitHub, so there will be a need to modify the implementation to either compress the output or split it into multiple smaller files, for instance.

I suggest reaching out to one of the members of the team at https://github.com/orgs/datasets/people for a resolution as I'm afraid I won't be taking any decision on that one. 🙂 

I hope you are doing well! 👋

**Pull request closed without merging**
